lyptt/struct

.rubocop.yml, lib/migrator/migrator.rb, lib/spec/writer/spec_writer_1_1_X.rb
=> Fixed issues with migrator choking on xcconfig-based projects

changelog.yml, examples/iOSTest/Specfile, lib/binsupport/struct_bin.rb, lib/xcodeproj/xcodeproj_writer.rb
=> Added support for specifying which variants to build

lib/xcodeproj/xcodeproj_writer.rb, spec/integration/support_files/xcodeproj_writer_test_source_precedence/Info.plist, spec/integration/support_files/xcodeproj_writer_test_source_precedence/project.yml, spec/integration/support_files/xcodeproj_writer_test_source_precedence/sources-2/Class.swift, spec/integration/support_files/xcodeproj_writer_test_source_precedence/sources-3/Class.swift, spec/integration/support_files/xcodeproj_writer_test_source_precedence/sources-4/Class.swift, spec/integration/support_files/xcodeproj_writer_test_source_precedence/sources/AppDelegate.swift, spec/integration/support_files/xcodeproj_writer_test_source_precedence/sources/Class.swift, spec/integration/xcodeproj_writer_spec.rb, spec/spec_helper.rb
=> Fixed source files precedence by swapping unshift for push, added test

lib/xcodeproj/xcodeproj_writer.rb, spec/integration/support_files/xcodeproj_writer_test_variant_filenames/project.yml, spec/integration/xcodeproj_writer_spec.rb
=> Improved variant naming when generating projects

lib/binsupport/struct_bin.rb, lib/migrator/migrator.rb, lib/refresher/refresher.rb, lib/spec/builder/spec_builder_12X/spec_target_dsl_12X.rb, lib/spec/builder/spec_builder_12X/spec_target_project_ref_dsl_12X.rb, lib/spec/parser/spec_parser_1_0_X.rb, lib/spec/parser/spec_parser_1_1_X.rb, lib/spec/parser/spec_parser_1_2_X.rb, lib/spec/writer/spec_writer_1_0_X.rb, lib/spec/writer/spec_writer_1_1_X.rb, lib/spec/writer/spec_writer_1_2_X.rb, lib/utils/ruby_2_0_monkeypatches.rb, lib/xcodeproj/xcodeproj_writer.rb, struct.gemspec
=> Fixed ruby 2.0.0 incompatibility issues

lib/binsupport/struct_bin.rb
=> Simplified struct invocations, and deprecated current invocations

lib/spec/builder/spec_builder_12X/spec_configuration_dsl_12X.rb, lib/spec/builder/spec_builder_12X/spec_file_dsl_12X.rb, lib/spec/builder/spec_builder_12X/spec_target_configuration_dsl_12X.rb, lib/spec/builder/spec_builder_12X/spec_target_dsl_12X.rb, lib/spec/builder/spec_builder_12X/spec_target_project_ref_dsl_12X.rb, lib/spec/builder/spec_builder_12X/spec_variant_dsl_12X.rb
=> Added defaults for every DSL method to avoid unhelpful ruby errors

.rubocop.yml, lib/spec/builder/spec_builder_12X/spec_configuration_dsl_12X.rb, lib/spec/builder/spec_builder_12X/spec_file_dsl_12X.rb, lib/spec/builder/spec_builder_12X/spec_target_configuration_dsl_12X.rb, lib/spec/builder/spec_builder_12X/spec_target_dsl_12X.rb, lib/spec/builder/spec_builder_12X/spec_target_project_ref_dsl_12X.rb, lib/spec/builder/spec_builder_12X/spec_variant_dsl_12X.rb, lib/spec/builder/spec_builder_13X/spec_configuration_dsl_13X.rb, lib/spec/builder/spec_builder_13X/spec_file_dsl_13X.rb, lib/spec/builder/spec_builder_13X/spec_target_configuration_dsl_13X.rb, lib/spec/builder/spec_builder_13X/spec_target_dsl_13X.rb, lib/spec/builder/spec_builder_13X/spec_target_project_ref_dsl_13X.rb, lib/spec/builder/spec_builder_13X/spec_variant_dsl_13X.rb, lib/spec/builder/spec_builder_dsl.rb, spec/support/spec_builder_12X/spec_builder_12X_test_43.rb, spec/support/spec_builder_13X/spec_builder_13X_test_43.rb, spec/unit/spec_builder_12X_spec.rb, spec/unit/spec_builder_13X_spec.rb
=> Fixed scope issues with DSL

lib/spec/builder/spec_builder_13X/spec_target_dsl_13X.rb, lib/xcodeproj/xcodeproj_writer.rb, spec/support/spec_builder_13X/spec_builder_13X_test_44.rb, spec/unit/spec_builder_13X_spec.rb
=> Added support for providing UUIDs for product_type

lib/spec/builder/spec_builder_13X/spec_target_dsl_13X.rb, lib/spec/parser/spec_parser_1_3_X.rb, lib/spec/spec_file.rb, lib/xcodeproj/source_flag_generator.rb, lib/xcodeproj/xcodeproj_writer.rb, spec/integration/support_files/xcodeproj_writer_test_source_options/Info.plist, spec/integration/support_files/xcodeproj_writer_test_source_options/project.yml, spec/integration/support_files/xcodeproj_writer_test_source_options/sources/AppDelegate.swift, spec/integration/support_files/xcodeproj_writer_test_source_options/sources/Class.m, spec/integration/xcodeproj_writer_spec.rb, spec/support/spec_builder_13X/spec_builder_13X_test_45.rb, spec/support/spec_parser_13X/spec_parser_13X_test_42.yml, spec/unit/spec_builder_13X_spec.rb, spec/unit/spec_parser_13X_spec.rb
=> Feature - compile flags

lib/xcodeproj/xcodeproj_writer.rb, spec/integration/support_files/xcodeproj_writer_test_file_excludes/Info.plist, spec/integration/support_files/xcodeproj_writer_test_file_excludes/project.yml, spec/integration/support_files/xcodeproj_writer_test_file_excludes/sources/AppDelegate.swift, spec/integration/support_files/xcodeproj_writer_test_file_excludes/sources/Class.m, spec/integration/support_files/xcodeproj_writer_test_file_excludes/sources/other/Class.m, spec/integration/xcodeproj_writer_spec.rb
=> Improved file excludes

lib/spec/builder/spec_builder_20X/spec_target_dsl_20X.rb, lib/spec/parser/spec_parser_2_0_X.rb, spec/support/spec_builder_20X/spec_builder_20X_test_46.rb, spec/support/spec_parser_20X/spec_parser_20X_test_43.yml, spec/unit/spec_builder_20X_spec.rb, spec/unit/spec_parser_20X_spec.rb
=> Added support for base target configuration

lib/spec/builder/spec_builder_20X/spec_file_dsl_20X.rb, lib/spec/parser/spec_parser_2_0_X.rb, lib/spec/processor/spec_processor.rb, lib/spec/processor/spec_scripts_processor.rb, lib/spec/spec_file.rb, spec/integration/processor_spec.rb, spec/integration/support_files/hooks_test/Info.plist, spec/integration/support_files/hooks_test/Specfile, spec/integration/support_files/hooks_test/post-generate.rb, spec/integration/support_files/hooks_test/pre-generate.rb, spec/integration/support_files/hooks_test/project.yml, spec/integration/support_files/hooks_test/sources/AppDelegate.swift, spec/spec_helper.rb, spec/support/processor/post-generate.rb, spec/support/processor/pre-generate.rb, spec/support/spec_builder_20X/spec_builder_20X_test_47.rb, spec/support/spec_parser_20X/spec_parser_20X_test_44.yml, spec/support/spec_parser_20X/support_files/post-generate.rb, spec/support/spec_parser_20X/support_files/pre-generate.rb, spec/unit/spec_builder_20X_spec.rb, spec/unit/spec_parser_20X_spec.rb, spec/unit/spec_scripts_processor_spec.rb
=> Added support for pre/post-generation hooks

lib/spec/spec_file.rb
=> Updated specfile models to be easier to construct

lib/spec/spec_file.rb, spec/integration/support_files/xcodeproj_writer_test_pod_references/Specfile
=> Feature configuration names

lib/spec/builder/spec_builder_20X/spec_file_dsl_20X.rb, spec/integration/support_files/xcodeproj_writer_test_pod_references/Specfile
=> Feature configuration shorthand

examples/iOS_Application/project.yml, lib/spec/builder/spec_builder_20X/spec_file_dsl_20X.rb, lib/spec/builder/spec_builder_20X/spec_scheme_dsl_20X.rb, lib/spec/builder/spec_builder_20X/spec_scheme_launch_dsl_20X.rb, lib/spec/builder/spec_builder_20X/spec_scheme_profile_dsl_20X.rb, lib/spec/builder/spec_builder_20X/spec_scheme_test_dsl_20X.rb, lib/spec/parser/spec_parser_2_0_X.rb, lib/spec/processor/scheme_archive_action.rb, lib/spec/processor/scheme_launch_action.rb, lib/spec/processor/scheme_profile_action.rb, lib/spec/processor/schemes.rb, lib/spec/spec_file.rb, lib/utils/defines.rb, spec/support/spec_builder_20X/spec_builder_20X_test_48.rb, spec/support/spec_parser_20X/spec_parser_20X_test_45.yml, spec/unit/spec_builder_20X_spec.rb, spec/unit/spec_parser_20X_spec.rb
=> Added support for declaring build configurations for all xcscheme phases

lib/spec/processor/spec_scripts_processor.rb
=> Fix post-generate hook depending on pre-generate

lib/spec/processor/project.rb
=> Enabled support for deterministic project generation

examples/iOS_Application/project.yml, lib/spec/builder/spec_builder_20X/spec_target_dsl_20X.rb, lib/spec/builder/spec_builder_20X/spec_target_script_dsl_20X.rb, lib/spec/parser/spec_parser_2_0_X.rb, lib/spec/processor/target_script.rb, lib/spec/spec_file.rb, lib/utils/type_helpers.rb, spec/integration/support_files/xcodeproj_writer_test_pre_post_run_scripts/project.yml, spec/support/spec_builder_20X/spec_builder_20X_test_51.rb, spec/support/spec_parser_20X/spec_parser_20X_test_48.yml, spec/unit/spec_builder_20X_spec.rb, spec/unit/spec_parser_20X_spec.rb
Should contribute to fixing #124
=> Added support for passing inputs, outputs and shell to run script phase

examples/iOS_Application/project.yml, lib/spec/builder/spec_builder_20X/spec_scheme_dsl_20X.rb, lib/spec/parser/spec_parser_2_0_X.rb, lib/spec/processor/scheme_analyze_action.rb, lib/spec/processor/schemes.rb, lib/spec/spec_file.rb, spec/support/spec_builder_20X/spec_builder_20X_test_52.rb, spec/support/spec_parser_20X/spec_parser_20X_test_49.yml, spec/unit/spec_builder_20X_spec.rb, spec/unit/spec_parser_20X_spec.rb
=> Added support for declaring analyze phase in schemes

lib/spec/processor/target_sources.rb
=> Bug pbxfile dotfolders
